version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.29
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventsproject_db
    ports:
      - 3310:3310
    volumes:
      - db:/var/lib/mysql
  app-eventsproject:
    depends_on:
      - mysqldb
    image: ashgodk/alpine:1.0.0
    #build : ./
    restart: on-failure
    ports:
      - 8090:8090
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3310/eventsproject_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'


    stdin_open: true
    tty: true

volumes:
  db :